# Generated by Django 2.1.1 on 2018-09-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comany',
            new_name='Company',
        ),
    ]
